name: Docker Run Hourly

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  run-docker:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
    steps:
      - name: Run Docker Container
        run: |
          docker run \
            --cap-add=NET_ADMIN \
            --device=/dev/net/tun \
            juriot/main
      
      - name: Restart workflow using curl
        if: always()
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/docker-run.yml/dispatches \
            -d '{"ref":"${{ github.ref }}"}'
